services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_MERCURE_URL=http://localhost:3001/.well-known/mercure
    volumes:
      - .:/app
    networks:
      - backend_api_network

networks:
  backend_api_network:
    external: true
